name: Ruff Lint Check

on:
  pull_request:
    branches:
      - '*'

jobs:
  ruf-lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up UV
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

      - name: Run ruff lint
        run: |
          uv run --only-group lint ruff check
